### ISSUE TITLE
Going from Colab to FaaS?

### ISSUE THREAD

**Issue by D1no** [cmrfrd/serverless_notebooks#1]
Hi Alexander, I saw your [thread on faas](https://github.com/openfaas/faas/issues/1030) a while ago and just stumbled over your investigation here after searching through the internet one more time.

I see that you bundled up jupyter — and thats great — but was thinking if it is not also worth investigating an isomorphic approach to deploy to a FaaS instance from anywhere. I.e. I use colab quite a bit (https://colab.research.google.com) since its convenient for collaboration.

I stumbled over clouderizer implementation of just adding a bang at the top of the notebook for deployment — maybe something like that would be worth investigating? 
https://help.clouderizer.com/running-on-cloud/google-colab/running-on-google-colab

![image](https://user-images.githubusercontent.com/2397125/52901035-16791900-31fe-11e9-9a60-bbeb73f6994e.png)

I'd love to do the same with my bare metal research server via FaaS... just how 🤔

Checkout this part of the video:
[![Video Notebook on Colab](https://user-images.githubusercontent.com/2397125/52901158-b2575480-31ff-11e9-820b-e3eb45b7d2ee.png)](https://youtu.be/CE0OOYIwcSw?t=55 "Notebook on Colab")

Anyway: Great work!

Dino

**Comment by cmrfrd** [comment]
Dino,

Thank you for the issue! If I'm understanding your idea correctly you want to take your existing notebook in google collab and deploy it to some exposed [faas-gateway](https://github.com/openfaas/faas/tree/master/gateway). There are a couple of ways this can be done.

1. Add it to the store

A round about way of doing this can be by submitting your own function to the [faas-store](https://github.com/openfaas/store) so any faas deployment can have access to it.

2. Download collab notebook and deploy via faas-cli

 Another way can be an analogous modification to what is being done in `deploy_notebook_function.ipynb` in this repo. The two adjustments would be that the notebook would need to be downloaded, then the environment variable `$OPENFAAS_URL` would need to be set to point to the correct openfaas gateway. 

Then using the `deploy_notebook` function passing in your downloaded notebook the docker image will be built, then deployed via the faas-cli.

I've used [this stackoverflow](https://stackoverflow.com/questions/38511444/python-download-files-from-google-drive-using-url) for quickly downloading files from drive.

Let me know if this helps :)

Alex

**Comment by D1no** [comment]
Mh, you are right... I could also write a bash script that installs and then uses the faas-cli on googles colab virtual machine to upload & deploy the function 🤔.

My goal is to deploy/update functions from an ipad.

**Comment by cmrfrd** [comment]
I think that's the best course of action. Unfortunately though it looks like [you can't run docker in google collab](https://stackoverflow.com/questions/49503893/how-to-run-docker-images-in-google-colaboratory). So you might have to do some weird fancy setup where you send your files to another machine to run docker and push your containers....

One detail I forgot to mention is that when you build your "function image" you do need to push it to a registry that openfaas is aware of (they use dockerhub). In the case of this repo I use the existing docker registry inside of minikube.

I'm closing this for now, but if I can find a way to integrate google collab notebooks into this repo I'll be sure to follow up :)
